/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ug.frontend;

import java.util.ArrayList;
import ug.backend.BazaDanych;
import ug.backend.Zajecia;

/**
 *
 * @author Agnieszka
 */
public class ZobaczTreningiFrame extends javax.swing.JFrame {

    /**
     * Creates new form ZobaczTreningiFrame
     */
    public ZobaczTreningiFrame() {
        initComponents();
        bd = new BazaDanych();
        zajecia = bd.pobierzZajecia();
        wyswietlZajecia(pozycja);
    }
    
     public void wyswietlZajecia(int pozycja){
        bPoprzedni.setEnabled(true);
        bKolejny.setEnabled(true);
        if(pozycja==0){
            bPoprzedni.setEnabled(false);
        }
        if (pozycja==zajecia.size()-1){
            bKolejny.setEnabled(false);
        }
    Zajecia z = zajecia.get(pozycja);
    lZajecia.setText(z.getZajecia_nazwa());
    lInstruktor.setText(z.getZajecia_instruktor());
    lDzien.setText(z.getZajecia_dzien_tygodnia());
    lGodzina.setText(z.getZajecia_godzina());
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lZajecia = new javax.swing.JLabel();
        lInstruktor = new javax.swing.JLabel();
        lDzien = new javax.swing.JLabel();
        lGodzina = new javax.swing.JLabel();
        bPoprzedni = new javax.swing.JButton();
        bKolejny = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jFrame1.setPreferredSize(new java.awt.Dimension(800, 450));
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));
        jPanel1.setForeground(new java.awt.Color(204, 0, 51));

        jLabel2.setBackground(new java.awt.Color(204, 0, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MOVE YOURSELF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel2)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jFrame1.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText("Zajecia:");
        jFrame1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Instruktor:");
        jFrame1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Dzień:");
        jFrame1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("Godzina:");
        jFrame1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        lZajecia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lZajecia.setText("jLabel7");
        jFrame1.getContentPane().add(lZajecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        lInstruktor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lInstruktor.setText("jLabel7");
        jFrame1.getContentPane().add(lInstruktor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        lDzien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lDzien.setText("jLabel7");
        jFrame1.getContentPane().add(lDzien, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        lGodzina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lGodzina.setText("jLabel7");
        jFrame1.getContentPane().add(lGodzina, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        bPoprzedni.setBackground(new java.awt.Color(255, 255, 255));
        bPoprzedni.setText("<");
        bPoprzedni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPoprzedniActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(bPoprzedni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        bKolejny.setBackground(new java.awt.Color(255, 255, 255));
        bKolejny.setText(">");
        bKolejny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKolejnyActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(bKolejny, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bPoprzedniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPoprzedniActionPerformed
        wyswietlZajecia(--pozycja);
    }//GEN-LAST:event_bPoprzedniActionPerformed

    private void bKolejnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKolejnyActionPerformed
        wyswietlZajecia(++pozycja);
    }//GEN-LAST:event_bKolejnyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZobaczTreningiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZobaczTreningiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZobaczTreningiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZobaczTreningiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZobaczTreningiFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKolejny;
    private javax.swing.JButton bPoprzedni;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lDzien;
    private javax.swing.JLabel lGodzina;
    private javax.swing.JLabel lInstruktor;
    private javax.swing.JLabel lZajecia;
    // End of variables declaration//GEN-END:variables
private BazaDanych bd;
    private ArrayList <Zajecia> zajecia;
private int pozycja;
}
